services:
    vite-preview:
        container_name: site-vite
        image: site-vite-preview:simp
        build:
            context: .
            dockerfile: Dockerfile.vite
        ports:
            - '${HOST_PORT_VITE}:${CONTAINER_PORT_VITE}'
        environment:
            - CONTAINER_PORT=${CONTAINER_PORT_VITE}
        env_file:
            - .env
        restart: unless-stopped

    nginx:
        container_name: site-nginx
        image: site-nginx:simp
        build:
            context: .
            dockerfile: Dockerfile.nginx
        ports:
            - '${HOST_PORT_NGINX}:${CONTAINER_PORT_NGINX}'
        environment:
            - CONTAINER_PORT=${CONTAINER_PORT_NGINX}
        env_file:
            - .env
        restart: unless-stopped

    serve:
        container_name: site-serve
        image: site-serve:simp
        build:
            context: .
            dockerfile: Dockerfile.serve
        ports:
            - '${HOST_PORT_SERVE}:${CONTAINER_PORT_SERVE}'
        environment:
            - CONTAINER_PORT=${CONTAINER_PORT_SERVE}
        env_file:
            - .env
        restart: unless-stopped
